apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing-dev
build:
  artifacts:
    - image: salkhon/ticketing-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
deploy:
  kubectl: {}