apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing-dev
build:
  artifacts: # syncing
    - image: salkhon/ticketing-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: salkhon/ticketing-client
      context: client
      sync:
        manual:
          - src: "**/*.{ts,tsx,js,jsx}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: salkhon/ticketing-tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: salkhon/ticketing-orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: salkhon/ticketing-expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: salkhon/ticketing-payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
deploy:
  kubectl: {}
