import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Ticketing App",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true}>
				{children}
			</body>
		</html>
	);
}
