apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-expiration
  template:
    metadata:
      labels:
        app: ticketing-expiration
    spec:
      containers:
        - name: ticketing-expiration
          image: salkhon/ticketing-expiration
          env:
            - name: CLUSTER_NAME
              value: ticketing
            - name: NATS_URL
              value: ticketing-nats-srv:4222
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: ticketing-expiration-redis-srv
