apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-orders
  template:
    metadata:
      labels:
        app: ticketing-orders
    spec:
      containers:
        - name: ticketing-orders
          image: salkhon/ticketing-orders # for GCP, use gcr.io/PROJECT-ID/image-name
          env:
            - name: MONGO_URI
              value: mongodb://ticketing-orders-mongo-srv:27017/orders
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: CLUSTER_NAME
              value: ticketing
            - name: NATS_URL
              value: ticketing-nats-srv:4222
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-orders-srv
spec:
  # default type is ClusterIP
  selector:
    app: ticketing-orders
  ports:
    - name: ticketing-orders
      protocol: TCP
      port: 3000
      targetPort: 3000
