apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-payments
  template:
    metadata:
      labels:
        app: ticketing-payments
    spec:
      containers:
        - name: ticketing-payments
          image: salkhon/ticketing-payments
          env:
            - name: MONGO_URI
              value: mongodb://ticketing-payments-mongo-srv:27017/payments
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: CLUSTER_NAME
              value: ticketing
            - name: NATS_URL
              value: ticketing-nats-srv:4222
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payments-srv
spec:
  # default type is ClusterIP
  selector:
    app: ticketing-payments
  ports:
    - name: ticketing-payments
      protocol: TCP
      port: 3000
      targetPort: 3000
