apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-tickets
  template:
    metadata:
      labels:
        app: ticketing-tickets
    spec:
      containers:
        - name: ticketing-tickets
          image: salkhon/ticketing-tickets
          env:
            - name: MONGO_URI
              value: mongodb://ticketing-tickets-mongo-srv:27017/ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-tickets-srv
spec:
  # default type is ClusterIP
  selector:
    app: ticketing-tickets
  ports:
    - name: ticketing-tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
