name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t salkhon/ticketing-expiration .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push salkhon/ticketing-expiration
      # we can install cloud CLI in workflow container and deploy to cloud provider here
