name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t salkhon/ticketing-client .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push salkhon/ticketing-client
      # we can install cloud CLI in workflow container and deploy to cloud provider here
